### ISSUE TITLE
Typo in an environment varialbe STATIC_ROOT_DEPLOY_PATH

### ISSUE THREAD

**Issue by koala-lava** [BirdBolt/alpine-nginx-uwsgi-django#1]
I think there's a typo in the compose file. 
```
volumes:
      - type: volume
        source: static_root_deploy_folder
        target: ${APP_SERVICE_ROOT_DIR}/${STATIC_ROOT_FOLDER_NAME}/
```

Instead of `${STATIC_ROOT_FOLDER_NAME} `I think it should be `STATIC_ROOT_DEPLOY_PATH`. Im not sure though Im trying to understand your config and docker in general.
Also the usage of .env file they say in documentation that it's not suited for `docker stack deploy` so I understand it's not swarm cluster build?
